# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=65)),
                ('year', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarMaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_maker', models.CharField(max_length=65)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='car_maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.CarMaker'),
        ),
    ]
