# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmaker',
            options={'permissions': (('Can view car_maker', 'can_view_car_maker'),)},
        ),
    ]
